<?php

use App\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list =  [
            [
                "ctr" => 1,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "Administration",
                "DepartmentNameJap" => "Administration",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "e-nishihira@hrd-s.com",
                "ProductionStaffEmails" => "htiadmin01@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 2,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HU",
                "DepartmentNameEng" => "Balcony",
                "DepartmentNameJap" => "Balcony",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-sugie@hrd-s.com",
                "ProductionStaffEmails" => "c-almazan@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 3,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HK",
                "DepartmentNameEng" => "Boiler",
                "DepartmentNameJap" => "Boiler",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-kitamura@hrd-s.com",
                "ProductionStaffEmails" => "hti-boiler03@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 4,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HG",
                "DepartmentNameEng" => "Ceramic Processing(Granite)",
                "DepartmentNameJap" => "Ceramic Processing(Granite)",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-fukunaga@hrd-s.com",
                "ProductionStaffEmails" => "c-mendoza@hrd-s.com",
                "FaCustotianEmails" => "m-ceramics@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [

                "ctr" => 5,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HT",
                "DepartmentNameEng" => "Ceramic Processing(Tile)",
                "DepartmentNameJap" => "Ceramic Processing(Tile)",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-naka@hrd-s.com,j-nakagaki@hrd-s.com",
                "ProductionStaffEmails" => "c-mendoza@hrd-s.com",
                "FaCustotianEmails" => "m-ceramics@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 6,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HT",
                "DepartmentNameEng" => "Ceramic Tile Production",
                "DepartmentNameJap" => "Ceramic Tile Production",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-naka@hrd-s.com,j-nakagaki@hrd-s.com",
                "ProductionStaffEmails" => "r-climacosa@hrd-s.com",
                "FaCustotianEmails" => "m-ceramics@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 7,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "Engineering",
                "DepartmentNameJap" => "Engineering",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "k-kumabe@hrd-s.com,n-ueda@hrd-s.com",
                "ProductionStaffEmails" => "j-carreon@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 8,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HU",
                "DepartmentNameEng" => "Exterior Unit",
                "DepartmentNameJap" => "Exterior Unit",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-sugie@hrd-s.com",
                "ProductionStaffEmails" => "h-diaz@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 9,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "FSE",
                "DepartmentNameJap" => "FSE",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "r-manalastas@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 10,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "i-cube Ceiling",
                "DepartmentNameJap" => "i-cube Ceiling",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "s-casajes@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 11,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "I-cube Insulation",
                "DepartmentNameJap" => "I-cube Insulation",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "m-miranda@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 12,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "i-cube Maintenance",
                "DepartmentNameJap" => "i-cube Maintenance",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "m-leandicho@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 13,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "I-cube Preparation",
                "DepartmentNameJap" => "I-cube Preparation",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "j-lopezjr@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 14,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "i-cube Production Control",
                "DepartmentNameJap" => "i-cube Production Control",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "j-bungcasan@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [

                "ctr" => 15,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "i-cube Roof-Gable",
                "DepartmentNameJap" => "i-cube Roof-Gable",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "m-dino@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 16,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "i-cube Tiling",
                "DepartmentNameJap" => "i-cube Tiling",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "a-rigon@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 17,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "i-cube Wall 1",
                "DepartmentNameJap" => "i-cube Wall 1",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "e-marquez@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 18,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "i-cube Wall 2",
                "DepartmentNameJap" => "i-cube Wall 2",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "s_deleon@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 19,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "i-cube Wall 3",
                "DepartmentNameJap" => "i-cube Wall 3",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "m-morishita@hrd-s.com,s-horibe@hrd-s.com",
                "ProductionStaffEmails" => "ht-icubeDHTprep@hrd-s.com",
                "FaCustotianEmails" => "i-cube_engineering@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 20,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HU",
                "DepartmentNameEng" => "I-Head",
                "DepartmentNameJap" => "I-Head",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-sugie@hrd-s.com",
                "ProductionStaffEmails" => "e-columna@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 21,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HN",
                "DepartmentNameEng" => "Insulation Molding",
                "DepartmentNameJap" => "Insulation Molding",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-nagasaka@hrd-s.com",
                "ProductionStaffEmails" => "r_jose@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 22,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HB",
                "DepartmentNameEng" => "IUB",
                "DepartmentNameJap" => "IUB",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "y-hirao@hrd-s.com",
                "ProductionStaffEmails" => "a-delacruz@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 23,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "Maintenance",
                "DepartmentNameJap" => "Maintenance",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "k-kumabe@hrd-s.com,t-kitamura@hrd-s.com,t-ishii@hrd-s.com",
                "ProductionStaffEmails" => "j-dalen@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 24,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "Material Control",
                "DepartmentNameJap" => "Material Control",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "production@hrd-s.com",
                "ProductionStaffEmails" => "f-manuel@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 25,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HU",
                "DepartmentNameEng" => "Panel Loading",
                "DepartmentNameJap" => "Panel Loading",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-sugie@hrd-s.com,ko-kido@hrd-s.com",
                "ProductionStaffEmails" => "c-vidallon@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 26,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HU",
                "DepartmentNameEng" => "Quality Assurance",
                "DepartmentNameJap" => "Quality Assurance",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "k-hanada@hrd-s.com,",
                "ProductionStaffEmails" => "c-vidallon@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 27,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HSX",
                "DepartmentNameEng" => "Siding(Common)",
                "DepartmentNameJap" => "Siding(Common)",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "h-kuida@hrd-s.com,a-miyao@hrd-s.com",
                "ProductionStaffEmails" => "hti-siding05@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 28,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HS",
                "DepartmentNameEng" => "Siding(Line1)",
                "DepartmentNameJap" => "Siding(Line1)",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "h-kuida@hrd-s.com,a-miyao@hrd-s.com",
                "ProductionStaffEmails" => "hti-siding05@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 29,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HW",
                "DepartmentNameEng" => "Siding(Line2)",
                "DepartmentNameJap" => "Siding(Line2)",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "h-kuida@hrd-s.com,a-miyao@hrd-s.com",
                "ProductionStaffEmails" => "hti-siding05@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 30,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HZ",
                "DepartmentNameEng" => "Siding(Line3)",
                "DepartmentNameJap" => "Siding(Line3)",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "h-kuida@hrd-s.com,a-miyao@hrd-s.com",
                "ProductionStaffEmails" => "hti-siding05@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 31,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HC",
                "DepartmentNameEng" => "Transport",
                "DepartmentNameJap" => "Transport",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "ko-kido@hrd-s.com",
                "ProductionStaffEmails" => "r-novero@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 32,
                "PayerCode" => "HT",
                "DcCode" => "",
                "AccountingCode" => "HU",
                "DepartmentNameEng" => "Unit Pipe",
                "DepartmentNameJap" => "Unit Pipe",
                "McJaEmails" => "ma-kato@hrd-s.com,r-yamaguchi@hrd-s.com,h-kameyama@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "n-mabute@hrd-s.com,htipayments@hrd-s.com",
                "ProductionJaEmails" => "t-sugie@hrd-s.com",
                "ProductionStaffEmails" => "m_villanueva@hrd-s.com",
                "FaCustotianEmails" => "hti-maintenance@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            //PVTECH
            [
                "ctr" => 33,
                "PayerCode" => "PV",
                "DcCode" => "",
                "AccountingCode" => "PX",
                "DepartmentNameEng" => "PH",
                "DepartmentNameJap" => "PH",
                "McJaEmails" => "y-fukuma@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "pvpurchasing@hrd-s.com",
                "ProductionJaEmails" => "y-aoki@hrd-s.com,m-ueda@hrd-s.com",
                "ProductionStaffEmails" => "pvenvi@hrd-s.com",
                "FaCustotianEmails" => "pvfacility@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 34,
                "PayerCode" => "PV",
                "DcCode" => "",
                "AccountingCode" => "PX",
                "DepartmentNameEng" => "PM",
                "DepartmentNameJap" => "PM",
                "McJaEmails" => "y-fukuma@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "pvpurchasing@hrd-s.com",
                "ProductionJaEmails" => "y-aoki@hrd-s.com,m-ueda@hrd-s.com",
                "ProductionStaffEmails" => "pvenvi@hrd-s.com",
                "FaCustotianEmails" => "pvfacility@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 35,
                "PayerCode" => "PV",
                "DcCode" => "",
                "AccountingCode" => "PX",
                "DepartmentNameEng" => "PV",
                "DepartmentNameJap" => "PV",
                "McJaEmails" => "y-fukuma@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "pvpurchasing@hrd-s.com",
                "ProductionJaEmails" => "y-aoki@hrd-s.com,m-ueda@hrd-s.com",
                "ProductionStaffEmails" => "pvenvi@hrd-s.com",
                "FaCustotianEmails" => "pvfacility@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 36,
                "PayerCode" => "PV",
                "DcCode" => "",
                "AccountingCode" => "PX",
                "DepartmentNameEng" => "Powerplant",
                "DepartmentNameJap" => "Powerplant",
                "McJaEmails" => "y-fukuma@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "pvpurchasing@hrd-s.com",
                "ProductionJaEmails" => "t-kitamura@hrd-s.com",
                "ProductionStaffEmails" => "powerplant01@hrd-s.com",
                "FaCustotianEmails" => "pvfacility@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 37,
                "PayerCode" => "PV",
                "DcCode" => "",
                "AccountingCode" => "PX",
                "DepartmentNameEng" => "Maintainance",
                "DepartmentNameJap" => "Maintainance",
                "McJaEmails" => "y-fukuma@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "pvpurchasing@hrd-s.com",
                "ProductionJaEmails" => "t-ishii@hrd-s.com",
                "ProductionStaffEmails" => "powerplant01@hrd-s.com",
                "FaCustotianEmails" => "pvfacility@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],

            //SCAD
            [
                "ctr" => 38,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Administration",
                "DepartmentNameJap" => "Administration",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "t-kujiraoka@hrd-s.com",
                "ProductionStaffEmails" => "employeerelation@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 39,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Cabinet",
                "DepartmentNameJap" => "Cabinet",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com",
                "ProductionStaffEmails" => "a-panganiban@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 40,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Door",
                "DepartmentNameJap" => "Door",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com,t-kimoto@hrd-s.com",
                "ProductionStaffEmails" => "k-lacumbes@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 41,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SX",
                "DepartmentNameEng" => "Floor-Piano(Flooring)",
                "DepartmentNameJap" => "Floor-Piano(Flooring)",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com,t-kimoto@hrd-s.com",
                "ProductionStaffEmails" => "h-pareja@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 42,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SW",
                "DepartmentNameEng" => "Floor-Piano(Wrapping Flooring)",
                "DepartmentNameJap" => "Floor-Piano(Wrapping Flooring)",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com,t-kimoto@hrd-s.com",
                "ProductionStaffEmails" => "h-pareja@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 43,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Floor-Piano(Others)",
                "DepartmentNameJap" => "Floor-Piano(Others)",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com",
                "ProductionStaffEmails" => "h-pareja@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 44,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "FSE",
                "DepartmentNameJap" => "FSE",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com",
                "ProductionStaffEmails" => "sc-pcotrainee@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 45,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Maintenance",
                "DepartmentNameJap" => "Maintenance",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "t-ishii@hrd-s.com,k-sugawara@hrd-s.com",
                "ProductionStaffEmails" => "maintenance@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 46,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Material Control",
                "DepartmentNameJap" => "Material Control",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "",
                "ProductionStaffEmails" => "a-gamboa@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 47,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Moulding",
                "DepartmentNameJap" => "Moulding",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com,",
                "ProductionStaffEmails" => "v-jordan@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 48,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Panel",
                "DepartmentNameJap" => "Panel",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com,t-kimoto@hrd-s.com",
                "ProductionStaffEmails" => "d_ferrer@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 49,
                "PayerCode" => "SC",
                "DcCode" => "",
                "AccountingCode" => "SF",
                "DepartmentNameEng" => "Quality Assurance",
                "DepartmentNameJap" => "Quality Assurance",
                "McJaEmails" => "k-seki@hrd-s.com,ma-terada@hrd-s.com,a-ikemori@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "smc-purchasing06@hrd-s.com,smc-purchasing02@hrd-s.com,smc-purchasing08@hrd-s.com,smc-purchasing12@hrd-s.com,smc-purchasing07@hrd-s.com",
                "ProductionJaEmails" => "h-utsuyama@hrd-s.com",
                "ProductionStaffEmails" => "sc-pcotrainee@hrd-s.com",
                "FaCustotianEmails" => "n_cabalse@scadmail.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],

            //WUKONG
            [
                "ctr" => 50,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "Administration",
                "DepartmentNameJap" => "Administration",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com,ma-yamamoto@hrd-s.com",
                "ProductionStaffEmails" => "hrd-training@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 51,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "FSE",
                "DepartmentNameJap" => "FSE",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com,ma-yamamoto@hrd-s.com",
                "ProductionStaffEmails" => "wkn-qa@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 52,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WL",
                "DepartmentNameEng" => "Glass(Laminated)",
                "DepartmentNameJap" => "Glass(Laminated)",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com,ma-yamamoto@hrd-s.com",
                "ProductionStaffEmails" => "m-baric@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 53,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WA",
                "DepartmentNameEng" => "Glass(Metal Accessories)",
                "DepartmentNameJap" => "Glass(Metal Accessories)",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com",
                "ProductionStaffEmails" => "m-baric@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 54,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WL",
                "DepartmentNameEng" => "Glass(Process Glass)",
                "DepartmentNameJap" => "Glass(Process Glass)",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com,ma-yamamoto@hrd-s.com",
                "ProductionStaffEmails" => "m-baric@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 55,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "Glass(Others)",
                "DepartmentNameJap" => "Glass(Others)",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com,ma-yamamoto@hrd-s.com",
                "ProductionStaffEmails" => "m-baric@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 56,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WW",
                "DepartmentNameEng" => "Glulam",
                "DepartmentNameJap" => "Glulam",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "i-odajima@hrd-s.com,h-nagae@hrd-s.com",
                "ProductionStaffEmails" => "wkn-hagara@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 57,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WW",
                "DepartmentNameEng" => "Hagara",
                "DepartmentNameJap" => "Hagara",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "i-odajima@hrd-s.com,h-nagae@hrd-s.com",
                "ProductionStaffEmails" => "j-dumol@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 58,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "Heavy Equipment Maintenance",
                "DepartmentNameJap" => "Heavy Equipment Maintenance",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "h-ogawa@hrd-s.com,k-okada@hrd-s.com",
                "ProductionStaffEmails" => "r-dinco@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 59,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "Maintenance",
                "DepartmentNameJap" => "Maintenance",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "k-kumabe@hrd-s.com",
                "ProductionStaffEmails" => "e-calderon@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 60,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "Material Control",
                "DepartmentNameJap" => "Material Control",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "",
                "ProductionStaffEmails" => "mc2-wkn@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 61,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WM",
                "DepartmentNameEng" => "Plastic Molding",
                "DepartmentNameJap" => "Plastic Molding",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "k-terao@hrd-s.com,k-oishi@hrd-s.com",
                "ProductionStaffEmails" => "j_castillo@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 62,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WW",
                "DepartmentNameEng" => "Preparation",
                "DepartmentNameJap" => "Preparation",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "i-odajima@hrd-s.com,h-nagae@hrd-s.com",
                "ProductionStaffEmails" => "j-dumol@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 63,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "QA",
                "DepartmentNameJap" => "QA",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com,ma-yamamoto@hrd-s.com",
                "ProductionStaffEmails" => "wkn-qa@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 64,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "Steel",
                "DepartmentNameJap" => "Steel",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "i-odajima@hrd-s.com,h-nagae@hrd-s.com",
                "ProductionStaffEmails" => "steel1@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 65,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WW",
                "DepartmentNameEng" => "Structural",
                "DepartmentNameJap" => "Structural",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "i-odajima@hrd-s.com,h-nagae@hrd-s.com",
                "ProductionStaffEmails" => "j-bolusa@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 66,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WH",
                "DepartmentNameEng" => "Window(Shade)",
                "DepartmentNameJap" => "Window(Shade)",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com,ma-yamamoto@hrd-s.com",
                "ProductionStaffEmails" => "m-baric@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 67,
                "PayerCode" => "WU",
                "DcCode" => "",
                "AccountingCode" => "WN",
                "DepartmentNameEng" => "Window(Others)",
                "DepartmentNameJap" => "Window(Others)",
                "McJaEmails" => "y-fukuma@hrd-s.com,s-kawahara@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "mc8-wkn@hrd-s.com,import-wkn@hrd-s.com",
                "ProductionJaEmails" => "t-yasui@hrd-s.com,ma-yamamoto@hrd-s.com",
                "ProductionStaffEmails" => "m-baric@hrd-s.com",
                "FaCustotianEmails" => "wkn-maint02@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            //HRD CAVITE
            [
                "ctr" => 69,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Accounting",
                "DepartmentNameJap" => "Accounting",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 70,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Administration",
                "DepartmentNameJap" => "Administration",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 71,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "CAD Design 1",
                "DepartmentNameJap" => "CAD Design 1",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 72,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "CAD Design 2",
                "DepartmentNameJap" => "CAD Design 2",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 73,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Denki",
                "DepartmentNameJap" => "Denki",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 74,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Estimation",
                "DepartmentNameJap" => "Estimation",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 75,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Exterior",
                "DepartmentNameJap" => "Exterior",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 76,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Frame",
                "DepartmentNameJap" => "Frame",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 77,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "FSE",
                "DepartmentNameJap" => "FSE",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 78,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Global Purchasing Center",
                "DepartmentNameJap" => "Global Purchasing Center",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 79,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "HACCHU",
                "DepartmentNameJap" => "HACCHU",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 80,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Heavy Equipment Maintenance",
                "DepartmentNameJap" => "Heavy Equipment Maintenance",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 81,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "House Presentation",
                "DepartmentNameJap" => "House Presentation",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 82,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "IQA",
                "DepartmentNameJap" => "IQA",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 83,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Logistics",
                "DepartmentNameJap" => "Logistics",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 84,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Original Hiroi",
                "DepartmentNameJap" => "Original Hiroi",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 68,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Panel Assembly",
                "DepartmentNameJap" => "Panel Assembly",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 85,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Piping",
                "DepartmentNameJap" => "Piping",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 86,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Plan Application",
                "DepartmentNameJap" => "Plan Application",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 87,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "QA",
                "DepartmentNameJap" => "QA",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 88,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "R&D",
                "DepartmentNameJap" => "R&D",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 89,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Security",
                "DepartmentNameJap" => "Security",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 90,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Structural Calculation 1",
                "DepartmentNameJap" => "Structural Calculation 1",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 91,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Structural Calculation 2",
                "DepartmentNameJap" => "Structural Calculation 2",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 92,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Structural Panel",
                "DepartmentNameJap" => "Structural Panel",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 93,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "Technical & Support",
                "DepartmentNameJap" => "Technical & Support",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 84,
                "PayerCode" => "HC",
                "DcCode" => "",
                "AccountingCode" => "RC",
                "DepartmentNameEng" => "UNIT WIRING",
                "DepartmentNameJap" => "UNIT WIRING",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 85,
                "PayerCode" => "HS",
                "DcCode" => "",
                "AccountingCode" => "HS",
                "DepartmentNameEng" => "H.R.D. SINGAPORE",
                "DepartmentNameJap" => "H.R.D. SINGAPORE",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 96,
                "PayerCode" => "ML",
                "DcCode" => "",
                "AccountingCode" => "ML",
                "DepartmentNameEng" => "Majestic",
                "DepartmentNameJap" => "Majestic",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 97,
                "PayerCode" => "ME",
                "DcCode" => "",
                "AccountingCode" => "ME",
                "DepartmentNameEng" => "Solar",
                "DepartmentNameJap" => "Solar",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 98,
                "PayerCode" => "DB",
                "DcCode" => "",
                "AccountingCode" => "BA",
                "DepartmentNameEng" => "Administration",
                "DepartmentNameJap" => "Administration",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],
            [
                "ctr" => 99,
                "PayerCode" => "DH",
                "DcCode" => "",
                "AccountingCode" => "CC",
                "DepartmentNameEng" => "DHCC",
                "DepartmentNameJap" => "DHCC",
                "McJaEmails" => "yo-kato@hrd-s.com,t-nakano@hrd-s.com,t-hamada@hrd-s.com",
                "McStaffEmails" => "gpc29@hrd-s.com,gpc32@hrd-s.com",
                "ProductionJaEmails" => "n-jingu@hrd-s.com",
                "ProductionStaffEmails" => "",
                "FaCustotianEmails" => "general-affairs03@hrd-s.com",
                "AccountingEmails" => "t-tanaka@hrd-s.com,n-jingu@hrd-s.com,j-takeshita@hrd-s.com"
            ],


        ];
        foreach ($list as $key => $val) {
            $list[$key]['id'] = $list[$key]['ctr'];
            unset($list[$key]['ctr']);
        }

        foreach ($list as $key => $val) {
            $dept = new Department;
            $dept->PayerCode = $list[$key]['PayerCode'];
            $dept->DcCode = $list[$key]['DcCode'];
            $dept->AccountingCode = $list[$key]['AccountingCode'];
            $dept->DepartmentNameEng = $list[$key]['DepartmentNameEng'];
            $dept->DepartmentNameJap = $list[$key]['DepartmentNameJap'];
            $dept->McJaEmails = $list[$key]['McJaEmails'];
            $dept->McStaffEmails = $list[$key]['McStaffEmails'];
            $dept->ProductionJaEmails = $list[$key]['ProductionJaEmails'];
            $dept->ProductionStaffEmails = $list[$key]['ProductionStaffEmails'];
            $dept->FaCustotianEmails = $list[$key]['FaCustotianEmails'];
            $dept->AccountingEmails = $list[$key]['AccountingEmails'];
            $dept->save();
        }
    }
}
